# Generated by Django 2.2.2 on 2019-07-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='reason',
            new_name='reference',
        ),
    ]
