# Generated by Django 2.2.2 on 2019-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20190719_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='reference',
            new_name='reason',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='note',
            field=models.TextField(default='Pending'),
        ),
    ]
