# Generated by Django 2.2.2 on 2019-07-21 17:23

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateField(default=attendance.models.today_date)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('ip', models.GenericIPAddressField(default='')),
                ('date_today', models.DateField(default=attendance.models.today_date, verbose_name='Date')),
                ('created_at', models.DateTimeField(default=attendance.models.time_stamp)),
                ('created_by', models.CharField(default='', max_length=20)),
            ],
            options={
                'unique_together': {('created_by', 'date_today')},
            },
        ),
    ]
